### ISSUE TITLE
Discuss: Remove StylableToolStrip

### ISSUE THREAD

**Issue by wolframhaussig** [Assorted-Development/winforms-stylable-controls#4]
Currently, `StylableToolStrip` does not contain any enhancements regarding styling. It only contains a fix for click handling when the parent does not have focus. I guess this control was moved here when we splitted the controls from our project as it was in the same folder as the other custom controls.

My proposal would be to remove it here and move it back to the using application.

**Comment by Nockiro** [comment]
I agree and therefore have created PR #7 to remove the control (and reintegrated it in the original project).
