### ISSUE TITLE
improve default settings for Colors

### ISSUE THREAD

**Issue by wolframhaussig** [Assorted-Development/winforms-stylable-controls#6]
The defaults for each control should be checked: In the `StylableTabControl` for example, when not setting colors (beside the BackgroundColor required because of #5), the text of the active TabPage vanishes:
![image](https://github.com/Assorted-Development/winforms-stylable-controls/assets/13997737/34769689-996c-44e9-aff0-f381f3f6719f)

**Comment by Nockiro** [comment]
Oh.. turns out, I've solved this with #9 too, I think. Feel free to check this and to close this issue if it's solved. 😄

**Comment by wolframhaussig** [comment]
@Nockiro The specific problem with the TabControl was solved, yes. But this issue was intended to check all components for their default values and I found 2 more issues in your example Form:
The StylableComboBox and StylableTextBox look good but when added to a page on a StylableTabControl without default text they vanish completely:

StylableTextBox:
![image](https://github.com/Assorted-Development/winforms-stylable-controls/assets/13997737/de22b3a5-961e-41d1-a83e-02da3674270d)

Standard Textbox:
![image](https://github.com/Assorted-Development/winforms-stylable-controls/assets/13997737/f9a1c18c-61c0-414e-9be5-d55d4983a677)

This is caused by the missing default border and/or the background being the same as the TabPage background
